### ISSUE TITLE
Image slider in mobile view 

### ISSUE THREAD

**Issue by harimurugan1989** [xceed-nitj/pro2-ece-eaicnitj#3]
Image slider is not visible in mobile view. Just show one image and move it or remove the image completely and adjust the unused space accordingly

**Comment by 164adityakumar** [comment]
image slider added to mobile view
![image](https://github.com/xceed-nitj/pro2-ece-eaicnitj/assets/98655260/82ff6566-0541-4cbd-8aaf-3fa10f3abbc8)

**Comment by harimurugan1989** [comment]
Remove it and push countdown up.  with this design it's not going well

**Comment by 164adityakumar** [comment]
![image](https://github.com/xceed-nitj/pro2-ece-eaicnitj/assets/98655260/948b0b34-fcad-4ad7-9736-e38d2199b8d8)
is this ok?

**Comment by 164adityakumar** [comment]
This issue is resolved
