### ISSUE TITLE
Add fillers like dots and arrows in the home page

### ISSUE THREAD

**Issue by harimurugan1989** [xceed-nitj/pro2-ece-eaicnitj#6]
Chk the below image. Add similar designs for whole home page mainly hero section. ![Screenshot_20240530_082655_Chrome.jpg](https://github.com/xceed-nitj/ece-eaicnitj/assets/88608850/74cd8f12-8db3-4fa0-b7d1-9dc8e681b7c8)

**Comment by 164adityakumar** [comment]
![image](https://github.com/xceed-nitj/pro2-ece-eaicnitj/assets/98655260/896559a2-9807-4e36-8e81-89731ae6307c)
![image](https://github.com/xceed-nitj/pro2-ece-eaicnitj/assets/98655260/d768b74a-3341-4a1f-a354-111f7890b258)
Which one of these look better?

**Comment by harimurugan1989** [comment]
Second one you can use with first design of dots in navbar bg.

**Comment by 164adityakumar** [comment]
![image](https://github.com/xceed-nitj/pro2-ece-eaicnitj/assets/98655260/99715150-82cc-4b83-b631-bcdb4fc110fb)
fillers have been added
